apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  labels:
    app: http-demo
  name: http-demo
  namespace: tr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-08-17T17:39:10+08:00"
      creationTimestamp: null
      labels:
        app: http-demo
    spec:
      containers:
        - args:
            - --port=80
          image: registry.cn-shanghai.aliyuncs.com/clp-test/tr-tracer:httptest
          imagePullPolicy: IfNotPresent
          name: http-demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: http-demo
spec:
  selector:
    app: http-demo
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-demo
  labels:
    name: http-demo
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-tr
spec:
  rules:
    - host: http-demo.colipu.com
      http:
        paths:
          - backend:
              serviceName: http-demo
              servicePort: 80
            path: /
            pathType: ImplementationSpecific
