// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Goods struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Bn                   string   `protobuf:"bytes,3,opt,name=Bn,proto3" json:"Bn,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	Pic                  string   `protobuf:"bytes,5,opt,name=Pic,proto3" json:"Pic,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime           int64    `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,8,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Goods) Reset()         { *m = Goods{} }
func (m *Goods) String() string { return proto.CompactTextString(m) }
func (*Goods) ProtoMessage()    {}
func (*Goods) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{0}
}

func (m *Goods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goods.Unmarshal(m, b)
}
func (m *Goods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goods.Marshal(b, m, deterministic)
}
func (m *Goods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goods.Merge(m, src)
}
func (m *Goods) XXX_Size() int {
	return xxx_messageInfo_Goods.Size(m)
}
func (m *Goods) XXX_DiscardUnknown() {
	xxx_messageInfo_Goods.DiscardUnknown(m)
}

var xxx_messageInfo_Goods proto.InternalMessageInfo

func (m *Goods) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Goods) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Goods) GetBn() string {
	if m != nil {
		return m.Bn
	}
	return ""
}

func (m *Goods) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Goods) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *Goods) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Goods) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Goods) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type IDRequest struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{1}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type PageRequest struct {
	PageIndex            uint32   `protobuf:"varint,1,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{2}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPageIndex() uint32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *PageRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// The response message containing the greetings
type BaseResponse struct {
	RequestID            string   `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{3}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *BaseResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *BaseResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GoodsResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	Data                 *Goods        `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GoodsResponse) Reset()         { *m = GoodsResponse{} }
func (m *GoodsResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsResponse) ProtoMessage()    {}
func (*GoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{4}
}

func (m *GoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsResponse.Unmarshal(m, b)
}
func (m *GoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsResponse.Marshal(b, m, deterministic)
}
func (m *GoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsResponse.Merge(m, src)
}
func (m *GoodsResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsResponse.Size(m)
}
func (m *GoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsResponse proto.InternalMessageInfo

func (m *GoodsResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GoodsResponse) GetData() *Goods {
	if m != nil {
		return m.Data
	}
	return nil
}

type GoodsListResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=BaseResponse,proto3" json:"BaseResponse,omitempty"`
	Total                uint64        `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Data                 []*Goods      `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GoodsListResponse) Reset()         { *m = GoodsListResponse{} }
func (m *GoodsListResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsListResponse) ProtoMessage()    {}
func (*GoodsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{5}
}

func (m *GoodsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsListResponse.Unmarshal(m, b)
}
func (m *GoodsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsListResponse.Marshal(b, m, deterministic)
}
func (m *GoodsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsListResponse.Merge(m, src)
}
func (m *GoodsListResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsListResponse.Size(m)
}
func (m *GoodsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsListResponse proto.InternalMessageInfo

func (m *GoodsListResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GoodsListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GoodsListResponse) GetData() []*Goods {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Goods)(nil), "pb.Goods")
	proto.RegisterType((*IDRequest)(nil), "pb.IDRequest")
	proto.RegisterType((*PageRequest)(nil), "pb.PageRequest")
	proto.RegisterType((*BaseResponse)(nil), "pb.BaseResponse")
	proto.RegisterType((*GoodsResponse)(nil), "pb.GoodsResponse")
	proto.RegisterType((*GoodsListResponse)(nil), "pb.GoodsListResponse")
}

func init() { proto.RegisterFile("goods.proto", fileDescriptor_a30593c5487368b0) }

var fileDescriptor_a30593c5487368b0 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdd, 0x8a, 0xd3, 0x50,
	0x10, 0x26, 0x3f, 0xcd, 0x36, 0x13, 0xbb, 0xb6, 0x87, 0xba, 0x84, 0xb8, 0x4a, 0xc8, 0x55, 0xd9,
	0x8b, 0x06, 0xab, 0x17, 0xa2, 0x17, 0x62, 0x1b, 0x28, 0x01, 0x95, 0x72, 0xba, 0x3e, 0xc0, 0x69,
	0x73, 0x08, 0x91, 0x6e, 0x4e, 0x6c, 0xce, 0x2e, 0xa2, 0xe8, 0x85, 0xaf, 0xe0, 0xf3, 0x78, 0xe3,
	0x2b, 0xf8, 0x0a, 0x3e, 0x88, 0x9c, 0xc9, 0x5f, 0xab, 0x82, 0x82, 0x77, 0xf3, 0x7d, 0x33, 0xdf,
	0x7c, 0x93, 0x39, 0x13, 0x70, 0x52, 0x21, 0x92, 0x72, 0x5a, 0xec, 0x85, 0x14, 0x44, 0x2f, 0x36,
	0xde, 0x79, 0x2a, 0x44, 0xba, 0xe3, 0x21, 0x2b, 0xb2, 0x90, 0xe5, 0xb9, 0x90, 0x4c, 0x66, 0x22,
	0xaf, 0x2b, 0x82, 0xaf, 0x1a, 0xf4, 0x96, 0x4a, 0x41, 0x4e, 0x41, 0x8f, 0x23, 0x57, 0xf3, 0xb5,
	0x89, 0x49, 0xf5, 0x38, 0x22, 0x04, 0xcc, 0x57, 0xec, 0x8a, 0xbb, 0xba, 0xaf, 0x4d, 0x6c, 0x8a,
	0xb1, 0xaa, 0x99, 0xe7, 0xae, 0x81, 0x8c, 0x3e, 0xcf, 0xc9, 0x18, 0x7a, 0xab, 0x7d, 0xb6, 0xe5,
	0xae, 0xe9, 0x6b, 0x13, 0x8d, 0x56, 0x80, 0x0c, 0xc1, 0x58, 0x65, 0x5b, 0xb7, 0x87, 0x65, 0x2a,
	0x24, 0x2e, 0x9c, 0x2c, 0x44, 0x2e, 0x79, 0x2e, 0x5d, 0x0b, 0xd9, 0x06, 0x92, 0xfb, 0x00, 0x8b,
	0x3d, 0x67, 0x92, 0x5f, 0x66, 0x57, 0xdc, 0x3d, 0xf1, 0xb5, 0x89, 0x41, 0x0f, 0x18, 0x95, 0x7f,
	0x5d, 0x24, 0x4d, 0xbe, 0x5f, 0xe5, 0x3b, 0x26, 0xb8, 0x0b, 0x76, 0x1c, 0x51, 0xfe, 0xf6, 0x9a,
	0x97, 0xf2, 0xd7, 0x4f, 0x08, 0x96, 0xe0, 0xac, 0x58, 0xca, 0x9b, 0xf4, 0x39, 0xd8, 0x0a, 0xc6,
	0x79, 0xc2, 0xdf, 0x61, 0xd5, 0x80, 0x76, 0x04, 0xf1, 0xa0, 0xaf, 0xc0, 0x3a, 0x7b, 0x5f, 0x7d,
	0xf3, 0x80, 0xb6, 0x38, 0x78, 0x03, 0xb7, 0xe6, 0xac, 0xe4, 0x94, 0x97, 0x85, 0xc8, 0x4b, 0xae,
	0x3a, 0xd5, 0x4d, 0x6b, 0x3f, 0x9b, 0x76, 0x04, 0x39, 0x03, 0x6b, 0x2d, 0x99, 0xbc, 0x2e, 0xb1,
	0x4f, 0x9f, 0xd6, 0x48, 0x6d, 0x74, 0x21, 0x12, 0x5e, 0xef, 0x0f, 0x63, 0xb5, 0xab, 0x97, 0x65,
	0x8a, 0xfb, 0xb3, 0xa9, 0x0a, 0x83, 0x04, 0x06, 0xf8, 0x20, 0xad, 0xd9, 0xa3, 0x63, 0x73, 0xf4,
	0x73, 0x66, 0xc3, 0x69, 0xb1, 0x99, 0x1e, 0xf2, 0xf4, 0x78, 0xc4, 0x7b, 0x60, 0x46, 0x4c, 0x32,
	0x1c, 0xc1, 0x99, 0xd9, 0xaa, 0xba, 0x6a, 0x8b, 0x74, 0xf0, 0x09, 0x46, 0x08, 0x5f, 0x64, 0xa5,
	0xfc, 0x4f, 0xa7, 0x31, 0xf4, 0x2e, 0x85, 0x64, 0x3b, 0xb4, 0x32, 0x69, 0x05, 0x5a, 0x7f, 0xc3,
	0x37, 0xfe, 0xe0, 0x3f, 0xfb, 0xa6, 0x43, 0x1f, 0xf1, 0xfa, 0x66, 0x4b, 0x9e, 0x82, 0x55, 0x3d,
	0x39, 0xe9, 0xea, 0xbc, 0xdf, 0x6c, 0x83, 0xf1, 0xe7, 0xef, 0x3f, 0xbe, 0xe8, 0xa7, 0x81, 0x1d,
	0xde, 0x3c, 0x08, 0xf1, 0xcc, 0x9f, 0x68, 0x17, 0x4a, 0x5c, 0xdd, 0xc3, 0x3f, 0x89, 0xbd, 0x63,
	0xf1, 0x63, 0xb0, 0x22, 0xbe, 0xe3, 0x7f, 0x13, 0x8f, 0x50, 0xec, 0x5c, 0x74, 0x62, 0xf2, 0x0c,
	0x8c, 0x25, 0x97, 0x64, 0xa0, 0x6a, 0xdb, 0x0b, 0xf4, 0x46, 0xdd, 0x77, 0x36, 0xda, 0x33, 0xd4,
	0x0e, 0xc9, 0x69, 0xab, 0x0d, 0x3f, 0xc4, 0xd1, 0x47, 0xf2, 0x1c, 0x4c, 0xb5, 0x7c, 0x72, 0x5b,
	0x49, 0x0e, 0xce, 0xd4, 0xbb, 0xd3, 0xf6, 0x38, 0x7c, 0x9c, 0x66, 0x06, 0xd2, 0xcd, 0xb0, 0xb1,
	0xf0, 0x1f, 0x7e, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0x00, 0x18, 0x8e, 0xb7, 0xf4, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodsSvcClient is the client API for GoodsSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsSvcClient interface {
	// Sends a greeting
	Create(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error)
	Update(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error)
	Delete(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error)
	Get(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*GoodsResponse, error)
	List(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*GoodsListResponse, error)
}

type goodsSvcClient struct {
	cc *grpc.ClientConn
}

func NewGoodsSvcClient(cc *grpc.ClientConn) GoodsSvcClient {
	return &goodsSvcClient{cc}
}

func (c *goodsSvcClient) Create(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsSvcClient) Update(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsSvc/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsSvcClient) Delete(ctx context.Context, in *Goods, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsSvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsSvcClient) Get(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*GoodsResponse, error) {
	out := new(GoodsResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsSvc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsSvcClient) List(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*GoodsListResponse, error) {
	out := new(GoodsListResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsSvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsSvcServer is the server API for GoodsSvc service.
type GoodsSvcServer interface {
	// Sends a greeting
	Create(context.Context, *Goods) (*BaseResponse, error)
	Update(context.Context, *Goods) (*BaseResponse, error)
	Delete(context.Context, *Goods) (*BaseResponse, error)
	Get(context.Context, *IDRequest) (*GoodsResponse, error)
	List(context.Context, *PageRequest) (*GoodsListResponse, error)
}

// UnimplementedGoodsSvcServer can be embedded to have forward compatible implementations.
type UnimplementedGoodsSvcServer struct {
}

func (*UnimplementedGoodsSvcServer) Create(ctx context.Context, req *Goods) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedGoodsSvcServer) Update(ctx context.Context, req *Goods) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedGoodsSvcServer) Delete(ctx context.Context, req *Goods) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedGoodsSvcServer) Get(ctx context.Context, req *IDRequest) (*GoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedGoodsSvcServer) List(ctx context.Context, req *PageRequest) (*GoodsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterGoodsSvcServer(s *grpc.Server, srv GoodsSvcServer) {
	s.RegisterService(&_GoodsSvc_serviceDesc, srv)
}

func _GoodsSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Goods)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSvcServer).Create(ctx, req.(*Goods))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsSvc_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Goods)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSvcServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsSvc/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSvcServer).Update(ctx, req.(*Goods))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Goods)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSvcServer).Delete(ctx, req.(*Goods))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsSvc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSvcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsSvc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSvcServer).Get(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsSvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSvcServer).List(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodsSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GoodsSvc",
	HandlerType: (*GoodsSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GoodsSvc_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GoodsSvc_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoodsSvc_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GoodsSvc_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GoodsSvc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
